In [5]:
import numpy as np

In [6]:
#Create array of integers from 1 to 10
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#Get the 8th element of the array
arr[8]

8

In [10]:
#get the first 5 elements of the array
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
#grab the last 5 elements of the array using slicing
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
#arrays can boardcast, unlike lists. Example:
arr[0:5] = 100
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
#reset array
arr = np.arange(0,11)

In [22]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:] = 99

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
#broadcasting is adjusting the elements of the array
#by reference. If you want a copy, use the a.copy() method
arr_copy = arr.copy()


In [28]:
arr_2d = np.array([[5,10,15],[2,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [ 2, 25, 30],
       [35, 40, 45]])

In [29]:
#select the element in the 2nd row, 2nd col
arr_2d[1][1]

25

In [35]:
arr_2d[(1,1)]

25

In [36]:
arr_2d[1,1]

25

In [37]:
#grab the top right corner of arr_2d
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [44]:
#np arrays can be used for conditional statements for each element in the array
arr = np.arange(1, 11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
#We can use arrays of boolean values for conditional selection
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#Practice selecting subsets of this:

In [49]:
arr_2d[3:, 2:]

array([[32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
arr_2d[2, 4:7]

array([24, 25, 26])