In [2]:
import pandas as pd

In [3]:
#Make sample Python built-in list
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
#Now import Pythons Linear Algebra library
import numpy as np

In [8]:
#Cast Python list as numpy array data structure and print to see difference
arr = np.array(my_list)
arr

array([1, 2, 3])

In [9]:
#Make sample Python built-in matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
#Cast Python list as numpy matrix data structure and print to see difference
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#np.arange creates sequence of number that is
#left inclusive and right exclusive
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#third parameters is stepsize
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
#np.zeros makes an array/matrix of zeros the parameter 
#is a tuple containing the desired dimensions
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#np.ones works similarly to np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#np.linspace will create an array that is evenly (or linearly)
#spaced. The number of elements in the array is determined
#by the third parameter
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
#np.eye creates the identity matrix
#(square matrix with all elements being 0 
#except 1's in the diagonal)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#There are methods extending np.random._____
#np.random.rand generates random numbers from ~Unif[0,1]
#The first parameter is the number of random elements
np.random.rand(5)

array([0.42649815, 0.30517442, 0.45776084, 0.71244781, 0.16773273])

In [21]:
#To create a matrix of random elements, pass dimensions
#as separate arguments. This is different from np.ones
#and np.zeros
np.random.rand(2,3)

array([[0.10680772, 0.87991586, 0.9098147 ],
       [0.25891761, 0.82147611, 0.10776117]])

In [18]:
#np.random.randn samples from ~N(0, 1)
np.random.randn(2, 3)

array([-2.75838306,  0.54318986])

In [46]:
#np.random.randint samples random integers that are
#left to right inclusive to exclusive.
np.random.randint(10, 15, 4)

array([10, 11, 10, 13])

In [56]:
#a.reshape will reshape the same data into matrix with
#specified dimensions
arr = np.arange(25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
#arr.max() gives the max value of the array
arr.max()

24

In [58]:
#arr.min() gives the min value of the array
arr.min()

0

In [59]:
#arr.argmax() gives the index at which the maximum point
#occurs
arr.argmax()

24

In [62]:
#arr.argmin() gives the index at which the minimum point
#occurs
arr.argmin()

0

In [64]:
#arr.shape returns the dimension of the array/matrix
arr.shape

(25,)

In [67]:
#Here is an example of using shape for a 3 dimensional matrix
np.random.randint(10, 15, 30).reshape(5,2,3).shape

(5, 2, 3)